### ISSUE TITLE
Code needs better formatting

### ISSUE THREAD

**Issue by pwab** [GodotDocMobile/godot_class_reference#2]
GDScript code examples inside the docs aren't formatted well. This could be improved by working around the following problems:

1. Codeboxes have no monospaced font (like [FiraCode](https://github.com/tonsky/FiraCode) or [Source Code Pro](https://github.com/adobe-fonts/source-code-pro))
2. Code isnt' highlighted (like with [CodeField](https://github.com/BertrandBev/code_field) but as far as I can see [flutter_highlight](https://pub.dev/packages/flutter_highlight) doesn't support GDScript yet)
3. Code is wrapped (make it scrollable with touch-input would be a better alternative)

I hope I have made my issues clear. If not I'll gladly add some screenshots for more explanation.

**Comment by fengjiongmax** [comment]
I have improving code/codeblock display in mind, but I'm too lazy to try them after I checking flutter_lighlight and know it does not support GDScript...

**Comment by pwab** [comment]
I looked into flutter_lighlight and its language specification. It could be possible to just copy the [python implementation](https://github.com/git-touch/highlight.dart/blob/master/highlight/lib/languages/python.dart) and use this as a starting point.

**Comment by fengjiongmax** [comment]
Just did some digging, I think in highlight.dart, supported language definition files were generated by [tools/highlight.js](https://github.com/git-touch/highlight.dart/blob/master/tool/highlight.js), and it requires the highlight.js library itself, which supports GDScript but need some extra work.  
Because GDScript.js does not exist in [highlight.js/src/languages/](https://github.com/highlightjs/highlight.js/tree/main/src/languages), and highlight.js support for GDScript is in [another repository](https://github.com/highlightjs/highlightjs-gdscript).  
This should work, thanks.

**Comment by fengjiongmax** [comment]
**code now can scroll horizontally**
![Screenshot_1633256161](https://user-images.githubusercontent.com/5288733/135749318-ef372d86-36f8-4f70-a131-269c7b2d1fb4.png)
![Screenshot_1633256177](https://user-images.githubusercontent.com/5288733/135749330-9aa76b36-76c2-4d2a-a0a0-59955e1cc636.png)
Will ship under version `0.2.0`, should be available in the next day or two.
Closing this, reopen if needed.

**Comment by pwab** [comment]
Looks super awesome! :+1:
